### ISSUE TITLE
Recovering faulty DB (java.lang.IllegalStateException: Store header is corrupt: nio:/a/keydb/keybox.mv.db [1.4.192/6])

### ISSUE THREAD

**Issue by fjoesne** [aditosoftware/docker-keybox#4]
Keybox is running and seems to be fine except that i cannot log into it after a reboot. At first I thought it was a time issue, as this has caused OTP issues before. Tailing keybox.trace.db from the host revealed messages such as: 

```
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Store header is corrupt: nio:/a/keydb/keybox.mv.db [1.4.192/6]" [50000-192]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        ... 132 more
Caused by: java.lang.IllegalStateException: Store header is corrupt: nio:/a/keydb/keybox.mv.db [1.4.192/6]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:605)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:355)
        ... 127 more

```

Could this be the cause of failure to log in? seems strange that the keybox starts at all if the DB is faulty. 

If a faulty DB-file is the reason, is there a way to check and recover the db? Seems like an awful single point of failure if I have to cut my losses and re-initialize the entire keybox from scratch. I guess It's my fault for not doing a regular backup. There is no evidence for disk-failure, so could the database be corrupted if the container is killed/stopped (powerloss etc)? .I'm concerned that this may cause problems on one of my more critical environments where i have deployed keybox as well.

**Comment by bdito** [comment]
I can´t help you with your issue. I only build the Docker-Image and I do not have any further information to this database. Also this issue never happened to me.
You should maybe ask the creator of Keybox: https://github.com/skavanagh/KeyBox
